### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yuntianming21** [Rushijaviya/Mezzo-Projects#10]
thank you for your sharing. when i running your code, there is a error. and I can't solve it. what follows is the error.
-----------------
Enter your choice : 7
[ WARN:0@3.668] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\grfmt_tiff.cpp (462) cv::TiffDecoder::readData OpenCV TIFF: TIFFRGBAImageOK: Sorry, can not handle images with 32-bit samples
Traceback (most recent call last):
  File "D:/python project/example2---bm3d/BM3D-Denoise-master/venv/transfrom.py", line 45, in <module>
    cv2.imwrite("Output Images/{}".format(new_image), img)
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:801: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'

------------------
I hoping you can help me. thanks

**Comment by Rushijaviya** [comment]
@Stapan17 Have a look into this.

**Comment by Stapan17** [comment]
> ## thank you for your sharing. when i running your code, there is a error. and I can't solve it. what follows is the error.
> Enter your choice : 7 [ WARN:0@3.668] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\grfmt_tiff.cpp (462) cv::TiffDecoder::readData OpenCV TIFF: TIFFRGBAImageOK: Sorry, can not handle images with 32-bit samples Traceback (most recent call last): File "D:/python project/example2---bm3d/BM3D-Denoise-master/venv/transfrom.py", line 45, in cv2.imwrite("Output Images/{}".format(new_image), img) cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:801: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'
> 
> I hoping you can help me. thanks

I have tested it with few images. it is running fine.
It would be better if you can send that particular image so, I can look into more details if it's not personal.

**Comment by yuntianming21** [comment]
![data1](https://user-images.githubusercontent.com/102347205/160224290-74c08f9f-366a-4fe6-b61f-1713b127e913.jpg)
——————————
This is the file to be converted. Please modify the file extension to tif, and then convert it to jpg. Because it doesn't support sending tif pictures. thanks!

**Comment by Stapan17** [comment]
Your image is not visible, please upload it properly or send the google drive link of the image, Thanks.

**Comment by yuntianming21** [comment]
![data1](https://user-images.githubusercontent.com/102347205/160229098-ec0da246-ae78-4125-b2ac-99fec7c46828.jpg)

**Comment by yuntianming21** [comment]
but i have no google drive. are there any other solutions?

**Comment by Stapan17** [comment]
will you be able to send it via email at testftestl4@gmail.com, then pls send it.

**Comment by yuntianming21** [comment]
I‘m already send this picture to your email. Please check your email. Thanks.

**Comment by Rushijaviya** [comment]
https://t.me/Savanitapan17 you can message here. He will resolve your issue.

**Comment by Rushijaviya** [comment]
Thank you for using the project.
